src/custom-template.mdx
This PR updates an outdated link for custom templating
=> fix: updated old custom renderer link

package.json, src/document-creator/document-creator.mdx
- Updated document for document creator with document storage documentation.
=> feat: updated documentation of document creator with document storage

src/document-creator/document-creator.mdx
This PR removes external site.
=> fix: remove ext site

docusaurus.config.js, sidebars.json
- https://www.pivotaltracker.com/story/show/176974412
- get algolia docsearch api key
- https://github.com/algolia/docsearch-configs/blob/master/configs/tradetrust.json
=> fix: algolia key

src/pages/index.tsx
- go to filtered tt docs directly
=> feat: tt docs link

docs/appendix/infrastructure-template.md, docs/appendix/tradetrust-api.md, docs/document-creator/config-file.md, docs/document-creator/overview.md, docs/tradetrust-website/info-bar.md
- Updated the documentations with Rinkeby urls and network
=> fix: added in rinkeby testnet urls

docs/overview/issuer-dns-txt-record.md
- added rinkeby testnet for issuer-dns-txt-record documentation
=> feat: added rinkeby for DNS record

docs/document-creator/config-file.md
https://www.pivotaltracker.com/story/show/179201536
Added documentation for wallet type integration
=> feat: add wallet type documentation

docs/overview/title-transfer-example.md, docs/overview/title-transfer.md, sidebars.json
This pull request details a guided example of a title transfer.
dont merge until the cli commands have been merged.
feel free to comment and improve upon the document.
=> feat: add example of title transfer

docs/document-creator/config-file/config-generator.md, docs/document-creator/config-file/file-structure.md, sidebars.json
- Updated config file docs
- added a section for config generation with oa-cli
https://www.pivotaltracker.com/n/projects/2424361
=> feat: update config file and add config generator

docs/document-creator/config-file/config-generator.md
- fix anchor link to step 2 of the documentation
=> fix/ fix anchor link on the page

src/css/styles.css, src/pages/index.tsx, tailwind.config.js
- updated the text and button design to be same as figma
=> chore: update homepage design

docs/appendix/infrastructure-template.md, docs/generic-templates/bill-of-lading.md, docs/generic-templates/cover-letter.md, docs/tradetrust-website/identity-resolution.md
=> chore: update text and links

docs/tradetrust-website/qr-code.md, sidebars.json
- brief explanation on qr code
- https://www.pivotaltracker.com/story/show/179294684
=> docs: qrcode

docs/advanced/aws-kms/did-sign-demo.md, docs/document-creator/config-file/config-generator.md, docs/document-creator/config-file/file-structure.md, docs/document-creator/prerequisites.md, docs/generic-templates/bill-of-lading.md, docs/generic-templates/cover-letter.md, docs/generic-templates/overview.md, docs/introduction/tradetrust-layer-boundaries.md, docs/technical/open-attestation.md
Update broken link that link to OA docs.
https://www.pivotaltracker.com/n/projects/2424361/stories/181307554
=> feat: update broken link to OA docs

docusaurus.config.js, package-lock.json, package.json, tailwind.config.js
- updated all deps to the latest
=> fix: update all deps to the latest

docs/tradetrust-website/endorsement-chain.md
Summary:
small pr to update text as requested.
https://www.pivotaltracker.com/story/show/183387556
=> fix: update wrong text

docs/appendix/tradetrust-api.md
update verify api docs to new endpoint
=> chore: verify api documentation

docs/appendix/infrastructure-template.md, docs/document-creator/config-file/config-generator.md, docs/document-creator/config-file/file-structure.md, docs/overview/issuer-dns-txt-record.md, docs/overview/title-transfer-example.md, docs/tradetrust-website/info-bar.md, docs/tradetrust-website/qr-code.md
Deprecate Ropsten and Rinkeby testnets
_In preparation for 27 Oct_
- deprecate Ropsten and Rinkeby
- Replace them with Goerli as default
https://www.pivotaltracker.com/n/projects/2424361/stories/183540460
=> feat: deprecate ropsten and rinkeby

docs/document-creator/config-file/file-structure.md
https://www.pivotaltracker.com/story/show/181366320
=> chore: add wallet warning

docs/introduction/what-is-tradetrust.md
https://www.pivotaltracker.com/story/show/183414775
=> chore: embed links

docs/document-creator/config-file/file-structure.md
=> docs: storage disclaimer

docs/document-creator/config-file/config-generator.md, docs/document-creator/config-file/file-structure.md, docs/overview/issuer-dns-txt-record.md, docs/overview/title-transfer-example.md, docs/tradetrust-website/info-bar.md
Replace goerli Testnet with Sepolia Testnet
=> fix: remove goerli testnet

docs/appendix/network-support.md
- remove goerli
https://www.pivotaltracker.com/story/show/185584305
=> chore: remove goerli

docs/topics/tradetrust-website/qr-code.md
https://www.pivotaltracker.com/story/show/185899751
=> feat: qrcode tt functions

docs/tutorial/verifiable-documents/overview.mdx
Fix broken link at tutorial page.
=> fix: update broken link

src/components/ContractCost/ContractCostTable/index.tsx, src/components/ContractCost/FiatLabel/FiatLabel.tsx, src/components/ContractCost/hooks/useFetchGasPrice.tsx
Summary
Add cost estimation for XDC and stability for price estimation table
Changes
- add price estimation for XDC and stability
- update table header text for each price table
- remove identity issuer column
Related Issues
https://tradetrust.atlassian.net/browse/TT-104
=> fix: tt 104 dynamic estimate of transaction costs

docs/getting-started/getting-started.md, docs/reference/libraries/tradetrust-core.md, sidebars.json
added a new section under references/libraries for tradetrust core
=> fix: add ref section doc for tradetrust core

docs/reference/tradetrust-v4/identity-vc-specifications.md, docs/reference/tradetrust-v4/idvc-overview.md, docs/reference/tradetrust-v4/issuing-v4-idvc-document.md, docs/reference/tradetrust-v4/obtaining-valid-idvc.md, docs/reference/tradetrust-v4/tradetrust-v4-schema.md, docs/reference/tradetrust-v4/verifying-v4-idvc-document.md, sidebars.json
Added in IDVC specs into TT v4 IDVC beta section
=> feat: added IDVC specs

docs/migration-guide/migration-tr-v5.md, docs/migration-guide/migration-tt-cli-v5.md, sidebars.json
- Added Migration to Tradetrust CLI
- Addition dependencies of ethers v6 and openzeppelin v5
=> fix: update docs

docs/topics/introduction/what-is-tradetrust.md
Updated the introduction with new paragraph.
[ Jira Ticket](https://afa-cdi.atlassian.net/browse/TT-462?atlOrigin=eyJpIjoiODRjMzU1NDBmZTBjNGMzN2FjYThjM2Q1ZDIxMjk5ZDgiLCJwIjoiaiJ9)
=> docs: update introduction

docs/how-tos/advanced/additional-network-metamask-guide.mdx, docs/introduction/key-components-of-tradetrust/blockchain/supported-network.md, sidebars.json, versioned_docs/version-4.x/topics/advanced/additional-network-metamask-guide.mdx
- Merged supported network list and updated note
- Add the Add Custom Network tab for v5 guide
- Added XDC network configs for support
- updated sidebars
Jira Ticket -
[TT-592](https://afa-cdi.atlassian.net/browse/TT-592?atlOrigin=eyJpIjoiYjMzNWM1NzIzOTVjNGMwY2IyYjc4YmY4MGJlZmIyZTAiLCJwIjoiaiJ9)
=> feat: update blockchain page and add tabs

docusaurus.config.js
Add algolia metatag for authentication to start crawling
=> feat: algolia metatag

docs/how-tos/issuer/did-web.md
=> fix: cli helper text
